create table attore (id integer not null, cognome varchar(255), nome varchar(255), primary key (id));
create table catalogo (id integer not null, descrizione varchar(255), id_tipologia integer, is_serie boolean, locandina varchar(255), media_recensioni float(53), titolo varchar(255), primary key (id));
create table genere (id integer not null, genere varchar(255), primary key (id));
create table genere_catalogo (id_genere integer not null, id_catalogo integer not null, primary key (id_catalogo, id_genere));
create table preferiti (id_utente integer not null, id_catalogo integer not null, primary key (id_catalogo, id_utente));
create table puntata (id_video integer not null, id_stagione integer not null, numero_puntata integer, primary key (id_stagione, id_video));
create table recensione (id_video integer not null, id_stagione integer not null, numero_puntata integer, primary key (id_stagione, id_video));
create table stagione (id integer not null, id_catalogo integer, numero_stagione integer, titolo_stagione varchar(255), primary key (id));
create table tipologia (id integer not null, tipologia varchar(255), primary key (id));
create table utente (id integer not null, email varchar(255), immagine varchar(255), nick_name varchar(255), password varchar(255), primary key (id));
create table video (id integer not null, durata varchar(255), id_catalogo integer, titolo varchar(255), primary key (id));
create table video_attore (id_video integer not null, id_attore integer not null, primary key (id_attore, id_video));
create table attore (id integer not null, cognome varchar(255), nome varchar(255), primary key (id));
create table catalogo (id integer not null, descrizione varchar(255), id_tipologia integer, is_serie boolean, locandina varchar(255), media_recensioni float(53), titolo varchar(255), primary key (id));
create table genere (id integer not null, genere varchar(255), primary key (id));
create table genere_catalogo (id_genere integer not null, id_catalogo integer not null, primary key (id_catalogo, id_genere));
create table preferiti (id_utente integer not null, id_catalogo integer not null, primary key (id_catalogo, id_utente));
create table puntata (id_video integer not null, id_stagione integer not null, numero_puntata integer, primary key (id_stagione, id_video));
create table recensione (id_video integer not null, id_stagione integer not null, numero_puntata integer, primary key (id_stagione, id_video));
create table stagione (id integer not null, id_catalogo integer, numero_stagione integer, titolo_stagione varchar(255), primary key (id));
create table tipologia (id integer not null, tipologia varchar(255), primary key (id));
create table utente (id integer not null, email varchar(255), immagine varchar(255), nick_name varchar(255), password varchar(255), primary key (id));
create table video (id integer not null, durata varchar(255), id_catalogo integer, titolo varchar(255), primary key (id));
create table video_attore (id_video integer not null, id_attore integer not null, primary key (id_attore, id_video));
